menu:
- {name: 'People', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Jake Iles-Smith', title: 'Senior Lecturer', department: 'Physics & Astronomy', institution: 'University of Sheffield', email: 'jake.iles-smith@manchester.ac.uk', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator',bio: True}
- {name: 'Oliver Dudgeon', title: 'PhD student', department: 'Physics & Astronomy', institution: 'University of Manchester', image: 'assets/img/graduate-student.jpg', url: 'graduate-student',bio: False}
- {name: 'Mateusz Salamon', title: 'PhD student', department: 'Physics & Astronomy', institution: 'University of Manchester', image: 'assets/img/graduate-student.jpg', url: 'graduate-student',bio: False}

courses:
- {name: 'Vector spaces', url: 'vector-calculus'}


social:
- {icon: 'github', link: 'https://github.com/jilessmith'}

academic:
- {icon: 'google-scholar', link: 'https://scholar.google.co.uk/citations?user=UpXSUTQAAAAJ&hl=en&inst=8574086807289546695'}

contacts:
- {name: 'Dr Jake Iles-Smith', title: 'Senior Lecturer', department: 'Physics & Astronomy', institution: 'University of Sheffield', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
